apiVersion: v1
kind: Service

metadata:
  name: devops-microservice-service

spec:
  selector:
    app: devops-microservice

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort